version: '3'

services:
  
  db:
    container_name: microservice_user-db
    image: mysql:5.7
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network

  app:
    container_name: microservice_user
    build: .
    command: sh -c "/wait && ./microservice_user"
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=20
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge