version: '3'

services:

  app:
    container_name: microservice_user
    build: .
    command: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    environment:
      WAIT_HOSTS: db:3306
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    container_name: microservice_user-db
    image: mysql:5.7
    #this command is important to mysql to run OK
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge